---
- name: 'Update apt cache'
  ansible.builtin.apt:
    update_cache: true

- name: 'Reload squid'
  ansible.builtin.service:
    name: 'squid'
    state: 'reloaded'

- name: 'Generate cache directory'
  ansible.builtin.command: squid -f /etc/squid/squid.conf -z -N
  changed_when: true
  listen: 'Generate squid cache'

- name: 'Restart squid'
  ansible.builtin.service:
    name: 'squid'
    state: 'restarted'
  listen: 'Generate squid cache'
