---
- name: 'Converge'
  hosts: 'all'
  tasks:
    - name: 'Configure APT'
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

    - name: 'Install test package'
      ansible.builtin.apt:
        name: 'ansible-apt-test-en'
        state: 'present'
        update_cache: true
  vars:
    apt_is_proxy_server: true
    debian_backports_enabled: true
    ansible_apt_other_repos__to_merge:
      - name: 'test-repo'
        url: 'http://repo.element-networks.nl'
        key_url: 'http://repo.element-networks.nl/public.gpg'
        release: 'ansible-test'
        repos: 'main'
    ansible_apt_proxy_direct__to_merge:
      - 'repo.element-networks.nl'
    apt_proxy_url: 'http://localhost:8000'
    apt_proxy_whitelist:
      - 'ftp.nl.debian.org'
      - 'repo.element-networks.nl'
